config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  namespace :admin do
    root to: "home#index"
    get    '/login',   to: 'sessions#new', as: 'new_session'
    post   '/login',   to: 'sessions#create', as: 'sessions'
    get    '/logout',  to: 'sessions#destroy', as: 'destroy_session'

    resources :albums
    resources :artists
    resources :genres
    resources :tracks
    resources :users
    
  end

end

app/models/administrator.rb
class Administrator < ApplicationRecord
	has_secure_password

	validates :first_name,
						:last_name,
						:email, presence: true
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  belongs_to :label

  has_many :artists

  has_one_attached :cover_image

  has_many :album_artists
  has_many :artists, through: :album_artists

  has_many :tracks, dependent: :nullify

  has_many :album_genres
  has_many :genres, through: :album_genres

  validates :title,
            :description, presence: true

  validates :title, uniqueness: { scope: :artist }
end

app/models/album_artist.rb
class AlbumArtist < ApplicationRecord
	belongs_to :album
	belongs_to :artist 
end

app/models/album_genre.rb
class AlbumGenre < ApplicationRecord
  belongs_to :album
  belongs_to :genre
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord

	has_many :album_artists
	has_many :albums, through: :album_artists

	validates :title, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :album_genres
	has_many :albums, through: :album_genres

	validates :title, presence: true
end

app/models/label.rb
class Label < ApplicationRecord
	has_many :albums, dependent: :nullify

	validates :title, presence: true
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :album

  acts_as_list scope: :album

  validates :title, presence: true
end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < Admin::BaseController

	def index
		@resource_name  	 = "Albums"
		@columns 			  	 = get_columns
		@current_page   	 = params[:current_page].try(:to_i) || 1
		@per_page 		  	 = params[:per_page].try(:to_i) || 10
		@sort_field		  	 = params[:sort_field] || 'id'
		joined_sort_field  = handle_associated_sort
		@sort_direction    = params[:sort_direction] || 'asc'

		@albums  			     = Album.all
		@total_count	 		 = @albums.count

		@query             = @albums.includes(:artist, :label).order("#{joined_sort_field} #{@sort_direction}").limit(@per_page).offset((@current_page - 1) * @per_page)
		


		@pages 				     = (@total_count.fdiv(@per_page)).floor 
		add_breadcrumb "Albums", :admin_albums
	end



	def new
		@album = Album.new
		add_breadcrumb "Albums", :admin_albums
		add_breadcrumb "New", :new_admin_album
	end


	def create
		add_breadcrumb "Albums", :admin_albums
		add_breadcrumb "New", :new_admin_album
		
		@album = Album.create(album_params)

		if @album.save
			flash[:success] = "Album successfully created."
			redirect_to admin_albums_path
		else
			render :new
		end
	end

	def edit
		add_breadcrumb "Albums", :admin_albums
		add_breadcrumb "Edit", :edit_admin_album
		@album = Album.find(params[:id])
	end

	def update
		add_breadcrumb "Albums", :admin_albums
		add_breadcrumb "Edit", :edit_admin_album

		@album = Album.find(params[:id])

		if @album.update(album_params)
			flash[:success] = "Album successfully updated."
			redirect_to edit_admin_album_path(@album)
		else
			render :edit
		end
	end



	private

	def album_params
		params.require(:album).permit(:title, :description, :release_date, :artist_id, :label_id, :available, :cover_image)
	end

	def get_columns
		[
			{ field: 'id', label: 'ID', type: 'integer' },
			{ field: 'title', label: 'Title', type: 'string' },
			{ field: 'release_date', label: 'Release Date', type: 'date' },
			{ field: 'artist', label: 'Artist', association_field: 'title', type: 'string' },
			{ field: 'label', label: 'Label', association_field: 'title', type: 'string' },
			{ field: 'available', label: 'Available', type: 'boolean' }
		]
	end


	def handle_associated_sort
		sort_mapping 			= @columns.select { |col| col[:field] == @sort_field }.try(:first)
		sort_field_string = sort_mapping[:association_field] ? "#{@sort_field.pluralize}.#{sort_mapping[:association_field]}" : @sort_field
	end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	layout "admin"
  before_action :authorize

  add_breadcrumb "Home", :admin_root

  def current_user
      @current_user ||= Administrator.find(session[:admin]["current_user_id"]) if session[:admin] && session[:admin]["current_user_id"]
  end
  helper_method :current_user

  private
  
  def authorize
      redirect_to admin_new_session_path unless current_user
  end	
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  def index
    
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::BaseController
  skip_before_action :authorize, only: [:new, :create]
  layout "admin_login"

  def new

  end

  def create
    user = Administrator.find_by(email: params[:session][:email])
    if user.nil?
      redirect_to admin_new_session_path
      flash[:error] = "Invalid Credentials. Please verify your credentials, and that you are an administrator."
    else
      session[:admin] = {}
      session[:admin]["current_user_id"] = user.id
      redirect_to admin_root_path
    end
  end

  def destroy
    session.delete(:admin)
    redirect_to admin_root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception, prepend: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "homepage"

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/table_helper.rb
module TableHelper


	def table_column(field)
		case field.class.name
		when "TrueClass", "FalseClass"
			self.boolean_column(field)
		when "Time", "Date", "DateTime"
			self.date_column(field)
		when "Fixnum", "Integer"
			self.integer_column(field)
		when "String"
			self.string_column(field)
		else
			# raise "UnknownFieldTypeError"
		end
	end

	

	def boolean_column(field)
		if field
			raw '<div class="col-md"><i class="fa fa-check"></i></div>'
		else
			raw '<div class="col-md"><i class="fa fa-times"></i></div>'
		end
	end

	def date_column(field)
		raw "<div class='col-md'>#{field.strftime('%b %e, %Y')}</div>"
	end

	def integer_column(field)
		raw "<div class='col-md'>#{field}</div>"
	end

	def string_column(field)
		raw "<div class='col-md'>#{field}</div>"
	end
end

app/views/admin/albums/_form.html.erb
<%= form_for [:admin, @album], class: "container" do |f| %>
		
		<div class="mb-5">
			<span>Basic information</span>
			<hr />
		</div>

		<div class="form-row">
	    <div class="form-group col-md-6">
				<%= f.label :title %>
				<%= f.text_field :title, class: "form-control #{" is-invalid" if @album.errors.messages[:title].present?}" %>

				<!-- validation messages -->
				<%= render partial: "admin/shared/bootstrap_form_errors", locals: { object: @album, field: :title } %>

			</div>
			
			<div class="form-group col-md-6">
				<%= f.label :release_date %>
				<%= datetime_field "album", "release_date", class: "form-control #{" is-invalid" if @album.errors.messages[:release_date].present?}" %>
				<!-- validation messages -->
				<%= render partial: "admin/shared/bootstrap_form_errors", locals: { object: @album, field: :release_date } %>
			</div>
		</div>

		<div class="form-group">
			<%= f.label :description %>
			<%= f.text_area :description, rows: "10", class: "form-control #{" is-invalid" if @album.errors.messages[:description].present?}" %>
			<!-- validation messages -->
			<%= render partial: "admin/shared/bootstrap_form_errors", locals: { object: @album, field: :description } %>
		</div>

		<div class="mb-5 mt-5">
			<span>Label information</span>
			<hr />
		</div>
		
		<div class="form-row">
			<div class="form-group col-md-12">
				<%= f.label :label %>
				<%= f.collection_select :label, Label.all, :id, :title, {selected: @album.label_id}, class: "form-control custom-select chosen-select #{" is-invalid" if @album.errors.messages[:label].present?}" %>
				<%= render partial: "admin/shared/bootstrap_form_errors", locals: { object: @album, field: :label } %>
			</div>
		</div>

		<div class="mb-5 mt-5">
			<span>Artist information</span>
			<hr />
		</div>

		<div class="form-row">	
			<div class="form-group col-md-12">
				<%= f.label :artist %>
				<%= f.collection_select :artist, Artist.all, :id, :title, {selected: @album.artist_id}, class: "form-control custom-select chosen-select #{" is-invalid" if @album.errors.messages[:artist].present?}" %>
				<%= render partial: "admin/shared/bootstrap_form_errors", locals: { object: @album, field: :artist } %>
			</div>
		</div>

		<div class="form-row">	
			<div class="form-group col-md-12">
				<%= f.label :accompanying_artists %>
				<%= f.collection_select :artist_ids, Artist.all, :id, :title, {selected: @album.artist_id}, class: "form-control custom-select chosen-select #{" is-invalid" if @album.errors.messages[:artist].present?}", multiple: true %>
				<%= render partial: "admin/shared/bootstrap_form_errors", locals: { object: @album, field: :artist } %>
			</div>
		</div>

		<div class="form-group form-row">
			<div class="form-check">	
				<%= f.check_box :available, class: "form-check-input" %>
				<%= f.label :available, class: "form-check-label"  %>
			</div>
		</div>


		<div class="mb-5 mt-5">
			<span>Images</span>
			<hr />
		</div>


		<div class="form-row">
			<div class="form-group col-md-6">
				<div class="custom-file custom-file--sm">
		  		<%= f.file_field :cover_image, class: "custom-file-input", id: "customFile" %>
		  		<label class="custom-file-label" for="customFile">Upload cover image</label>
				</div>
			</div>


			<div class="form-group col-md-6">
				<div class="custom-file custom-file--sm">
		  		<%= f.file_field :cover_image, class: "custom-file-input", id: "customFile" %>
		  		<label class="custom-file-label" for="customFile">Upload album art</label>
				</div>
			</div>
		</div>

		<div class="form-group form-row mt-5">
			<%= f.submit class: 'btn btn-primary' %>
		</div>

	<% end %> 

app/views/admin/albums/edit.html.erb
<div class="container">

	<div class="jumbotron bg-white">
	  <div class="container">
	    <h1 class="display-4">Edit an Album</h1>
	    <p class="lead">Inspect or update details for the selected album below.</p>
	  </div>
	</div>

	<%= render "/admin/albums/form" %>
</div>

app/views/admin/albums/index.html.erb
<%= render partial: "/admin/shared/bootstrap_table", 
	locals: {
		resource_name: @resource_name,
		columns: @columns,
		rows: @query,
		page: @current_page,
		per_page: @per_page,
		count: @total_count,
		sort_field: @sort_field,
		sort_direction: @sort_direction
	}
%>

app/views/admin/albums/new.html.erb
<div class="container">

	<div class="jumbotron bg-white">
	  <div class="container">
	    <h1 class="display-4">Create an Album</h1>
	    <p class="lead">Enter details for the new album below.</p>
	  </div>
	</div>

	<%= render "/admin/albums/form" %>
</div>

app/views/admin/home/index.html.erb
Admin Home

app/views/admin/shared/_bootstrap_form_errors.html.erb
<% if object.errors.messages[field.to_sym].present? %>
	<span class="invalid-feedback d-block">
    <% object.errors.messages[field.to_sym].each do |error| %>
    	<%= error %>
  	<% end %>
  </span>
<% end %>

app/views/admin/shared/_bootstrap_table.html.erb
<div class="container custom-table pl-10 pr-10 pb-20">
  <div class="jumbotron jumbotron-fluid pb-10 bg-white">
    <div class="container pl-0">

      <div class="row align-items-center justify-content-end">

        <div class="col-12 col-md-6">
          <h3>
            <%= resource_name %> <a href="/admin/<%= resource_name.downcase %>/new" class="btn btn-sm btn-outline-primary ml-1"><i class="fa fa-plus"></i></a><br>
            <small class="text-muted">Search, filter, and inspect <%=  resource_name.downcase %> here.</small>
          </h3>
        </div>

        <div class="col-12 col-md-6">
          <form action="<%= admin_albums_path(per_page: per_page, page: page, sort_field: sort_field, sort_direction: sort_direction) %>" method="POST
            " class="form-inline float-left float-md-right">

            <div class="form-group mx-sm-3">
              <input type="text" name="q" class="form-control" id="q" placeholder="Search">
              <button type="submit" class="btn btn-primary">Search</button>
            </div>
            
          </form>
        </div>
        
      </div>

    </div>
  </div>

  <div class="row d-none d-md-flex justify-content-start border-bottom">

    <% columns.each_with_index do |column, i| %>
        <div class="col-md custom-table--header">
         
          <% if sort_field == column[:field] && sort_direction == 'asc' %>
            <%= link_to admin_albums_path(per_page: per_page, page: page, sort_field: column[:field], sort_direction: 'desc') do %>
              <%= column[:label] %>
              <a class="fa fa-arrow-down"></a>
            <% end %>
          <% elsif sort_field == column[:field] && sort_direction == 'desc' %>
            <%= link_to admin_albums_path(per_page: per_page, page: page, sort_field: column[:field], sort_direction: 'asc') do %>
              <%= column[:label] %>
              <a class="fa fa-arrow-up"></a>
            <% end %>
          <% else %>
            <%= link_to admin_albums_path(per_page: per_page, page: page, sort_field: column[:field], sort_direction: 'asc') do %>
              <%= column[:label] %>
            <% end %>
          <% end %>
        </div>
    <% end %>

  </div>
  

  <% rows.each_with_index do |row, i| %>
  
    <%= link_to edit_admin_album_path(row.id), class: 'custom-table--data-row' do %>
      <div class="row align-items-center justify-content-start border-bottom <%= "bg-light" if i.even? %>">

        <% columns.each do |column| %>
          <% if column[:association_field] %>
            <%= table_column(row.send(column[:field]).send(column[:association_field])) %>
          <% else %>
            <%= table_column(row.send(column[:field])) %>
          <% end %>
        <% end %>

      </div>
    <% end %>

      <div class="row spacer d-sm-flex d-md-none">
        <div class="col"></div>
      </div>
      
  <% end %>
    
</div>

<%= render partial: "admin/shared/pagination" %>

app/views/admin/shared/_pagination.html.erb
<div class="pt-3">
	<nav aria-label="admin table navigation">
	  <ul class="pagination justify-content-center">

	  	<li class="page-item <%= "disabled" if @current_page == 1 %>"><a class="page-link" href="#">Previous</a></li>

	  	<% @pages.times do |page| %>

		  	<li class="page-item <%= "active" if @current_page == page + 1 %>">
		  		<%= link_to page + 1, admin_albums_path(current_page: page + 1, per_page: 10, sort_direction: @sort_direction, sort_field: @sort_field), class: "page-link" %>
	  		</li>

	    <% end %>

	    <li class="page-item <%= "disabled" if @current_page == @pages %>"><a class="page-link" href="#">Next</a></li>

	  </ul>
	</nav>
</div>

app/views/home/index.html.erb
Template

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuminusHD2</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'admin_style' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>


    <div id="wrapper" class="toggled">

        <!-- Sidebar -->
        <%= render "shared/sidebar" %>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
              
              
              <%= render "shared/breadcrumbs" %>

              <%= render "shared/flash_alerts" %>

              <%= yield %>

            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->



  </body>
</html>

app/views/layouts/admin_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuminusHD2</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin_login', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'admin_login_style' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>


    <div id="wrapper">

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">

              <%= render "shared/flash_alerts" %>

              <%= yield %>

            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->



  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuminusHD2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuminusHD2</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'homepage', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'home_style' %>
    

  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_breadcrumbs.html.erb
<div class="container pl-0 pr-0">
  <div class="inner">
     <ol class="breadcrumb bg-white">
        <!-- <a href="#menu-toggle" id="menu-toggle" class="menu-toggle mr-3"><i class="fa fa-bars fa-2x"></i></a> -->
       <% if @breadcrumbs %>
         <% @breadcrumbs.each_with_index do |bc, index| %>
           <% if index == (@breadcrumbs.count - 1) %>
              <li class="breadcrumb-item active"><%= bc.name %></li>
           <% else %>
              <li class="breadcrumb-item"><%= link_to bc.name, bc.path %></li>
           <% end %>
          <% end %>
       <% end %>
    </ol>
  </div>
</div>

app/views/shared/_flash_alerts.html.erb
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div id="sidebar-wrapper" class="toggled">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <a href="#">
        LuminusHD CMS
      </a>
    </li>
    <li>
      <a href="/admin"><i class="fa fa-tachometer pr-1"></i>Dashboard</a>
    </li>
    <li>
      <a href="/admin/albums"><i class="fa fa-book pr-1"></i>Albums</a>
    </li>
    <li>
      <a href="/admin/artists"><i class="fa fa-user-circle pr-1"></i>Artists</a>
    </li>
    <li>
      <a href="/admin/genres"><i class="fa fa-briefcase pr-1"></i>Genres</a>
    </li>
    <li>
      <a href="/admin/tracks"><i class="fa fa-play pr-1"></i>Tracks</a>
    </li>
    <li>
      <a href="/admin/orders"><i class="fa fa-cart-arrow-down pr-1"></i>Orders</a>
    </li>
    <li>
      <a href="/admin/users"><i class="fa fa-users pr-1"></i>Users</a>
    </li>
  </ul>
</div>